import type { Metadata } from "next";
import "./globals.css";
import { ThemeProvider } from "@/providers/theme-provider"
import { Header } from "@/components/shared/header";

export const metadata: Metadata = {
    title: "AstronomIA",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html 
            lang="en" 
            suppressHydrationWarning
        >
            <body>
                <ThemeProvider
                    attribute="class"
                    defaultTheme="system"
                    enableSystem
                    disableTransitionOnChange
                >
                    <div className="mx-10 lg:mx-50">
                        <Header />
                        {children}
                    </div>
                </ThemeProvider>
            </body>
        </html>
    );
}
